### PR TITLE
Extract sys data and remove sys object deletion

### PR DESCRIPTION
**Pull request by elvingm**
@jescalan Do we want to move ahead here with making the transformation disabled by default?
If so, I can peak into the docs and update that. Just need to know details about how we notify users of that particular breaking change.

### CODE REVIEW

**Comment by jescalan** [comment]
I think we should, although I'd like to get @tmilewski to sign off here as well since he originally wrote it!

**Comment by tmilewski** [comment]
I don't think that we should disable by default but rather make it very clear that they can disable it should they want to.

**Comment by jescalan** [comment]
We have had a lot of bug reports come in related to it. I think it might be easier to have the transform be opt-in rather than opt-out.

**Comment by jescalan** [comment]
Postponing discussion of defaults till later to get this specific fix shipped!

**Pull request merged**
