### PR TITLE
Add tests for contentful and locals in template

### PR DESCRIPTION
**Pull request by MathieuLoutre**
This is #76 but with tests for both `contentful` and `locals` used in a template.

### CODE REVIEW

**Comment by MathieuLoutre** [comment]
I have tried to put all the tests in the same folder in fixtures (`template`) but having other files in there caused a similar bug to what's happening in #74. Calling them `template-locals.html` and `template-contentful.html` even with nothing inside resulted in:

```message: `Module build failed: TypeError: Cannot read property 'fields' of undefined␊
        at eval (eval at <anonymous> (/Users/Otter/Programming/spike-contentful/node_modules/reshape-code-gen/lib/scoped_eval.js:9:15), <anonymous>:1:155)␊
        at eval (eval at <anonymous> (/Users/Otter/Programming/spike-contentful/node_modules/reshape-code-gen/lib/scoped_eval.js:9:15), <anonymous>:1:176)␊
        at evalNode (/Users/Otter/Programming/spike-contentful/node_modules/reshape-eval-code/lib/index.js:27:72)␊
        at util.modifyNodes (/Users/Otter/Programming/spike-contentful/node_modules/reshape-eval-code/lib/index.js:21:40)␊
        at when.resolve.then (/Users/Otter/Programming/spike-contentful/node_modules/reshape-plugin-util/lib/index.js:26:29)␊
        at tryCatchReject (/Users/Otter/Programming/spike-contentful/node_modules/when/lib/makePromise.js:845:30)␊
        at runContinuation1 (/Users/Otter/Programming/spike-contentful/node_modules/when/lib/makePromise.js:804:4)␊
        at Fulfilled.when (/Users/Otter/Programming/spike-contentful/node_modules/when/lib/makePromise.js:592:4)␊
        at ContinuationTask.run (/Users/Otter/Programming/spike-contentful/node_modules/when/lib/makePromise.js:702:24)␊
        at Scheduler._drain (/Users/Otter/Programming/spike-contentful/node_modules/when/lib/Scheduler.js:62:19)␊
        at Scheduler.drain (/Users/Otter/Programming/spike-contentful/node_modules/when/lib/Scheduler.js:27:9)␊
        at _combinedTickCallback (internal/process/next_tick.js:73:7)␊
        at process._tickCallback (internal/process/next_tick.js:104:9)`,
  }```

I can open a separate issue for this or continue on #74 if that's of interest.

**Comment by MathieuLoutre** [comment]
Any chance for this to be merged? It's really useful to have access to locals in templates.

**Comment by jescalan** [comment]
Yeah, I'm sorry! Have been busy this month. Will get this out shortly. Thanks for the contribution :tada:

**Comment by MathieuLoutre** [comment]
That's awesome thanks! I know how it gets sometimes, no worries :)

**Comment by whynotthough** [comment]
thank you @MathieuLoutre ! I'll do my best next time @jescalan :)

**Comment by MathieuLoutre** [comment]
@whynotthough You did all the hard work, I just wrote the tests ;)

**Pull request merged**
